# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50.0 
    #
# Position Controllers ---------------------------------------
joint1_position_controller:
  type: position_controllers/JointPositionController
  joint: j1
  pid: {p: 100.0, i: 0.01, d: 10.0}
joint2_position_controller:
  type: position_controllers/JointPositionController
  joint: j2
  pid: {p: 100.0, i: 0.01, d: 10.0}
joint3_position_controller:
  type: position_controllers/JointPositionController
  joint: j3
  pid: {p: 100.0, i: 0.01, d: 10.0}
joint4_position_controller:
  type: position_controllers/JointPositionController
  joint: j4
  pid: {p: 100.0, i: 0.01, d: 10.0}
joint5_position_controller:
  type: position_controllers/JointPositionController
  joint: j5
  pid: {p: 100.0, i: 0.01, d: 10.0}
joint6_position_controller:
  type: position_controllers/JointPositionController
  joint: j6
  pid: {p: 100.0, i: 0.01, d: 10.0}

# Trajectory Controllers ---------------------------------------
mitsubishi_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - j1
    - j2
    - j3
    - j4
    - j5
    - j6
  constraints:
    goal_time: 1.0                   # Override default
    j1:
      trajectory: 1.0
    j2:
      trajectory: 1.0
    j3:
      trajectory: 1.0
    j4:
      trajectory: 1.0
    j5:
      trajectory: 1.0
    j6:
      trajectory: 1.0

